Added --help option to git-state

diff --git a/bin/git-state b/bin/git-state
--- a/bin/git-state
+++ b/bin/git-state
@@ -4,11 +4,38 @@
 # A more concise and comprehensive version of `git status` and `git log` in one command.
 #
 
-while getopts ":h" opt; do
+help()
+{
+    man git-state
+    return
+}
+
+while getopts ":h-:" opt; do
     case $opt in
-        h)  man git-state; exit 0;;
-        \?) echo "Invalid option: -$OPTARG" >&2; exit 1;;
-        *)  echo "Unimplemented option: -$OPTARG" >&2; exit 1;;
+        -)
+            case "${OPTARG}" in
+                help)
+                    help
+                    exit 0
+                    ;;
+                *)
+                    echo "Unimplemented option --${OPTARG}" >&2
+                    exit 1
+                    ;;
+            esac
+            ;;
+        h)
+            help
+            exit 0
+            ;;
+        \?) 
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
+        *)  
+            echo "Unimplemented option: -$OPTARG" >&2
+            exit 1
+            ;;
     esac
 done
 
